export interface ArticleInterface {
    id: number;
    titre: String;
    rubrique: String;
    description: String;
}

export const touteLesArticles = [
    {id: 1, titre: "C'est quoi l'informatique ?", rubrique: "informatique", description: "L'informatique est un domaine d'activité scientifique, technique, et industriel concernant le traitement automatique de l'information numérique par l'exécution de programmes informatiques hébergés par des dispositifs électriques-électroniques : des systèmes embarqués, des ordinateurs, des robots, des automates, etc.Ces champs d'application peuvent être séparés en deux branches. <br/>   théorique : concerne la définition de concepts et modèles     pratique : s'intéresse aux techniques concrètes de mise en œuvre.   <br/> Certains domaines de l'informatique peuvent être très abstraits, comme la complexité algorithmique, et d'autres peuvent être plus proches d'un public profane. Ainsi, la théorie des langages demeure un domaine davantage accessible aux professionnels formés (description des ordinateurs et méthodes de programmation), tandis que les métiers liés aux interfaces homme-machine (IHM) sont accessibles à un plus large public."},

    {id: 2, titre: "C'est quoi un ordinateur ?", rubrique: "informatique", description: "Un ordinateur est un système de traitement de l'information programmable tel que défini par Alan Turing et qui fonctionne par la lecture séquentielle d'un ensemble d'instructions, organisées en programmes, qui lui font exécuter des opérations logiques et arithmétiques. <br/> Sa structure physique actuelle fait que toutes les opérations reposent sur la logique binaire et sur des nombres formés à partir de chiffres binaires. <br/>Dès sa mise sous tension, un ordinateur exécute, l'une après l'autre, des instructions qui lui font lire, manipuler, puis réécrire un ensemble de données déterminées par une mémoire morte d'amorçage. Des tests et des sauts conditionnels permettent de passer à l'instruction suivante et donc d'agir différemment en fonction des données ou des nécessités du moment ou de l'environnement."},
    {id: 3, titre: "C'est quoi un Périphérique ?", rubrique: "informatique", description: "Un périphérique informatique est un dispositif connecté à un système de traitement de l'information central (ordinateur, console de jeu, etc.1) et qui ajoute à ce dernier des fonctionnalités.<br/> On peut classer généralement les périphériques en trois types : les périphériques d'entrée, ceux de sortie et ceux qui agissent dans les deux sens autrement dit périphériques de stockage ou d'entrée-sortie . <br/> Ils servent à obtenir des informations (ou données) pour le système informatique tel qu'un clavier (frappe de texte), une souris (pointage), un scanner (numérisation de documents papier), un micro, une webcam, etc."},


    {id: 4, titre: "On peut parler de propreté ?", rubrique: "hygene", description: "La propreté est l'absence de souillure , incluant poussière, tache, et mauvaises odeurs. Elle implique des procédés de nettoyage, notamment dans le domaine de l'hygiène alimentaire (« élimination des souillures, des résidus d'aliments, de la saleté, de la graisse ou de toute autre matière indésirable »1). On peut parler de propreté pour un organisme vivant (homme, animal de compagnie) ou pour un lieu, une pièce.<br/>"},

    {id: 5, titre: "Comment se nettoyer ?", rubrique: "hygene", description: "Le nettoyage est le processus d'élimination des substances indésirables, telles que la saleté, les agents infectieux et autres impuretés, d'un objet ou d'un environnement. Le nettoyage se produit dans de nombreux contextes différents et utilise de nombreuses méthodes différentes. Plusieurs métiers sont consacrés au nettoyage. Le nettoyage a différents objectifs dont la propreté et l'hygiène, etc. <br/> Le nettoyage a lieu dans divers contextes commerciaux, domestiques, personnels et environnementaux, qui diffèrent par leur échelle et leurs exigences. <br/> Le nettoyage est généralement réalisé par une action mécanique et/ou une action de solvant ; de nombreuses méthodes reposent sur les deux processus."},

    {id: 6, titre: "C'est quoi une hygiène ?", rubrique: "hygene", description: "L'hygiène est un ensemble de mesures destinées à prévenir les infections et l'apparition de maladies infectieuses. Elle se base essentiellement sur trois actions.<br/> Il est possible de distinguer l'hygiène domestique et l'hygiène du corps. Par extension, on parle aussi d'« hygiène de vie », d'« hygiène alimentaire » et d'« hygiène mentale » pour des actions et activités permettant de prévenir l'apparition de troubles, comme la pratique d'un sport, l'abstention de fumer ou de boire de l'alcool. <br/>Le médecin Hippocrate, le premier hygiéniste connu de l'Antiquité, s'efforce d'utiliser l'hygiène à des fins curatives mais aussi préventives. Il écrit trois livres sur le régime consacrés à la diététique, la propreté et l'hygiène, dans lesquels il préconise les exercices corporels, la pratique de bains thérapeutiques et la modération dans les consommations (tempérance alimentaire, sobriété alcoolique)1. Platon attribue l'invention de la gymnastique médicinale au médecin Hérodicus de Lentini qui avait constaté les effets bénéfiques de l'exercice physique sur la santé"}
]